services:
  dvbi_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INSTALL_LOCATION=http://192.168.1.99:8080
      - STREAMIQ_SERVICELIST_URI=https://dvbi-demo.de-demo.b.stream-iq.net/servicelist
    restart: on-failure
    ports:
      - "8080:80"
