name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        IMAGE_TAG=dvbi-reference-client:$(date +%s)
        docker build . --file Dockerfile --tag ghcr.io/pvdheijden/$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.ACTIONS_TOKEN }}" | docker login ghcr.io -u pvdheijden --password-stdin
    - name: Push the Docker image
      run: |
        docker push ghcr.io/pvdheijden/$IMAGE_TAG
        echo "::set-output name=image_tag::$IMAGE_TAG"
